services:
  - type: web
    name: consumet-api # Name of the service
    env: docker
    repo: https://github.com/The-RJ-Studios/Manga-API.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 3000
